server:
  port: 8081
  servlet:
    context-path: /crud
    
spring:
  application:
    name: crud
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
   
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/crud?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    
      
